version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1231234
      POSTGRES_DB: vpn-bot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d vpn-bot" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: